version: 2
registries:
  private-github:
    type: git
    url: https://github.com:443/skuroki/dog
    username: x-access-token
    password: ${{secrets.DEPENDABOT_GITHUB_TOKEN}}
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - private-github
